"""§3.14.12 系统字段种子定义。"""
from __future__ import annotations

from typing import Any

from app.models.crm import (
    CONTRACT_STATUSES,
    CONTRACT_TYPES,
    DEAL_SOURCES,
    ORDER_SOURCES,
    ORDER_STATUSES,
    PAYMENT_METHODS,
    PAYMENT_STATUSES,
    QUOTE_STATUSES,
)

COMMON_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "created_by_user_id",
        "label": "创建人",
        "field_type": "user_ref",
        "is_system": True,
        "show_in_list_default": False,
        "storage": "db",
        "sort_order": 900,
    },
    {
        "field_key": "created_at",
        "label": "创建时间",
        "field_type": "datetime",
        "is_system": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 910,
    },
    {
        "field_key": "updated_at",
        "label": "最后修改时间",
        "field_type": "datetime",
        "is_system": True,
        "show_in_list_default": False,
        "storage": "db",
        "sort_order": 920,
    },
    {
        "field_key": "owner_user_id",
        "label": "负责人",
        "field_type": "user_ref",
        "is_system": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 930,
    },
    {
        "field_key": "territory_id",
        "label": "归属地区",
        "field_type": "territory_ref",
        "is_system": True,
        "show_in_list_default": False,
        "storage": "db",
        "sort_order": 940,
    },
]

LEAD_SOURCE_OPTIONS = [
    "官网",
    "公众号",
    "小红书",
    "抖音",
    "线下",
    "转介绍",
    "电话",
    "导入",
    "Webhook",
    "营销活动",
    "其他",
]
INDUSTRY_OPTIONS = ["制造", "零售", "餐饮", "科技", "服务业", "其他"]
COMPANY_SCALE_OPTIONS = ["1-10", "11-50", "51-200", "201-500", "500+ 人"]
TAXPAYER_TYPE_OPTIONS = ["一般纳税人", "小规模", "未知"]
ACCOUNTING_NEED_OPTIONS = ["新注册代账", "转代账", "报税辅导", "合规咨询", "其他"]
INTENTION_LEVEL_OPTIONS = ["高", "中", "低"]
LEAD_STATUS_OPTIONS = ["待跟进", "跟进中", "有意向", "无意向", "已转化", "无效"]

LEAD_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "lead_number",
        "label": "线索编号",
        "field_type": "text",
        "is_required": False,
        "show_in_list_default": True,
        "is_unique": True,
        "storage": "db",
        "sort_order": 5,
    },
    {
        "field_key": "company_name",
        "label": "公司名称",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {"field_key": "credit_code", "label": "统一社会信用代码", "field_type": "text", "sort_order": 20},
    {
        "field_key": "contact_name",
        "label": "联系人姓名",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 40,
    },
    {
        "field_key": "mobile",
        "label": "手机",
        "field_type": "phone",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 50,
    },
    {"field_key": "phone", "label": "电话", "field_type": "phone", "storage": "db", "sort_order": 60},
    {"field_key": "wechat", "label": "微信", "field_type": "text", "sort_order": 70},
    {"field_key": "qq", "label": "QQ", "field_type": "text", "sort_order": 75},
    {"field_key": "email", "label": "邮箱", "field_type": "email", "storage": "db", "sort_order": 80},
    {"field_key": "website", "label": "网址", "field_type": "url", "sort_order": 85},
    {"field_key": "province", "label": "省", "field_type": "text", "sort_order": 90},
    {"field_key": "city", "label": "市", "field_type": "text", "sort_order": 100},
    {"field_key": "district", "label": "区/县", "field_type": "text", "sort_order": 110},
    {"field_key": "address", "label": "详细地址", "field_type": "text", "sort_order": 120},
    {
        "field_key": "industry",
        "label": "行业",
        "field_type": "select",
        "options": INDUSTRY_OPTIONS,
        "show_in_list_default": True,
        "sort_order": 130,
    },
    {
        "field_key": "company_scale",
        "label": "公司规模",
        "field_type": "select",
        "options": COMPANY_SCALE_OPTIONS,
        "sort_order": 140,
    },
    {"field_key": "annual_revenue", "label": "年营业额", "field_type": "currency", "placeholder": "请输入金额", "sort_order": 150},
    {
        "field_key": "taxpayer_type",
        "label": "纳税人类型",
        "field_type": "select",
        "options": TAXPAYER_TYPE_OPTIONS,
        "sort_order": 170,
    },
    {"field_key": "main_business", "label": "主营业务", "field_type": "textarea", "sort_order": 180},
    {
        "field_key": "accounting_need",
        "label": "代账需求",
        "field_type": "select",
        "options": ACCOUNTING_NEED_OPTIONS,
        "sort_order": 190,
    },
    {
        "field_key": "source",
        "label": "线索来源",
        "field_type": "select",
        "options": LEAD_SOURCE_OPTIONS,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 200,
    },
    {"field_key": "source_detail", "label": "来源说明", "field_type": "text", "sort_order": 210},
    {
        "field_key": "status",
        "label": "线索状态",
        "field_type": "select",
        "options": LEAD_STATUS_OPTIONS,
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 220,
    },
    {
        "field_key": "intention_level",
        "label": "意向等级",
        "field_type": "select",
        "options": INTENTION_LEVEL_OPTIONS,
        "show_in_list_default": True,
        "sort_order": 230,
    },
    {
        "field_key": "campaign_id",
        "label": "市场活动",
        "field_type": "ref",
        "storage": "db",
        "sort_order": 240,
    },
    {
        "field_key": "next_follow_up_at",
        "label": "下次跟进时间",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 250,
    },
    {
        "field_key": "last_follow_up_at",
        "label": "最后跟进时间",
        "field_type": "datetime",
        "show_in_list_default": True,
        "sort_order": 260,
    },
    {"field_key": "last_follow_up_content", "label": "最后跟进内容", "field_type": "text", "sort_order": 270},
    {"field_key": "remark", "label": "备注", "field_type": "textarea", "storage": "db", "sort_order": 280},
    {
        "field_key": "converted_customer_id",
        "label": "已转客户",
        "field_type": "ref",
        "storage": "db",
        "sort_order": 290,
    },
]

CUSTOMER_STATUS_OPTIONS = ["潜在", "意向", "成交", "在服", "暂停", "流失"]
CUSTOMER_LEVEL_OPTIONS = ["A重点", "B普通", "C长尾"]
SERVICE_TYPE_OPTIONS = ["代理记账", "税务申报", "工商注册", "合规顾问"]

CUSTOMER_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "customer_number",
        "label": "客户编号",
        "field_type": "text",
        "is_required": False,
        "show_in_list_default": True,
        "is_unique": True,
        "storage": "db",
        "sort_order": 5,
    },
    {
        "field_key": "company_name",
        "label": "客户名称",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {"field_key": "short_name", "label": "客户简称", "field_type": "text", "sort_order": 20},
    {
        "field_key": "customer_level",
        "label": "客户级别",
        "field_type": "select",
        "options": CUSTOMER_LEVEL_OPTIONS,
        "show_in_list_default": True,
        "sort_order": 30,
    },
    {
        "field_key": "status",
        "label": "客户状态",
        "field_type": "select",
        "options": CUSTOMER_STATUS_OPTIONS,
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 40,
    },
    {
        "field_key": "mobile",
        "label": "主手机",
        "field_type": "phone",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 50,
    },
    {"field_key": "phone", "label": "主电话", "field_type": "phone", "storage": "db", "sort_order": 60},
    {"field_key": "email", "label": "邮箱", "field_type": "email", "sort_order": 70},
    {"field_key": "wechat", "label": "微信", "field_type": "text", "sort_order": 80},
    {"field_key": "province", "label": "省", "field_type": "text", "sort_order": 90},
    {"field_key": "city", "label": "市", "field_type": "text", "sort_order": 100},
    {"field_key": "district", "label": "区/县", "field_type": "text", "sort_order": 110},
    {"field_key": "address", "label": "详细地址", "field_type": "text", "sort_order": 120},
    {
        "field_key": "industry",
        "label": "行业",
        "field_type": "select",
        "options": INDUSTRY_OPTIONS,
        "show_in_list_default": True,
        "sort_order": 130,
    },
    {
        "field_key": "company_scale",
        "label": "公司规模",
        "field_type": "select",
        "options": COMPANY_SCALE_OPTIONS,
        "sort_order": 140,
    },
    {"field_key": "credit_code", "label": "统一社会信用代码", "field_type": "text", "sort_order": 150},
    {
        "field_key": "taxpayer_type",
        "label": "纳税人类型",
        "field_type": "select",
        "options": TAXPAYER_TYPE_OPTIONS,
        "sort_order": 160,
    },
    {"field_key": "legal_representative", "label": "法定代表人", "field_type": "text", "sort_order": 170},
    {"field_key": "registered_capital", "label": "注册资本", "field_type": "currency", "sort_order": 180},
    {
        "field_key": "service_type",
        "label": "服务类型",
        "field_type": "multiselect",
        "options": SERVICE_TYPE_OPTIONS,
        "sort_order": 190,
    },
    {"field_key": "service_start_at", "label": "服务开始日期", "field_type": "date", "sort_order": 200},
    {"field_key": "contract_amount", "label": "合同金额", "field_type": "currency", "sort_order": 210},
    {
        "field_key": "campaign_id",
        "label": "首次获客活动",
        "field_type": "ref",
        "storage": "db",
        "sort_order": 220,
    },
    {
        "field_key": "converted_from_lead_id",
        "label": "来源线索",
        "field_type": "ref",
        "storage": "db",
        "sort_order": 230,
    },
    {
        "field_key": "next_follow_up_at",
        "label": "下次跟进时间",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 240,
    },
    {
        "field_key": "last_follow_up_at",
        "label": "最后跟进时间",
        "field_type": "datetime",
        "show_in_list_default": True,
        "sort_order": 250,
    },
    {"field_key": "remark", "label": "备注", "field_type": "textarea", "storage": "db", "sort_order": 260},
]

CONTACT_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "name",
        "label": "姓名",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {
        "field_key": "gender",
        "label": "性别",
        "field_type": "select",
        "options": ["男", "女", "未知"],
        "sort_order": 20,
    },
    {"field_key": "title", "label": "职位", "field_type": "text", "storage": "db", "sort_order": 30},
    {"field_key": "department", "label": "部门", "field_type": "text", "storage": "db", "sort_order": 40},
    {"field_key": "mobile", "label": "手机", "field_type": "phone", "storage": "db", "sort_order": 50},
    {"field_key": "phone", "label": "电话", "field_type": "phone", "storage": "db", "sort_order": 60},
    {"field_key": "wechat", "label": "微信", "field_type": "text", "storage": "db", "sort_order": 70},
    {"field_key": "email", "label": "邮箱", "field_type": "email", "storage": "db", "sort_order": 80},
    {
        "field_key": "is_primary",
        "label": "首要联系人",
        "field_type": "checkbox",
        "storage": "db",
        "sort_order": 90,
    },
    {
        "field_key": "is_decision_maker",
        "label": "是否决策人",
        "field_type": "checkbox",
        "storage": "db",
        "sort_order": 100,
    },
    {"field_key": "remark", "label": "备注", "field_type": "textarea", "storage": "db", "sort_order": 110},
]

TASK_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "task_number",
        "label": "任务编号",
        "field_type": "text",
        "is_required": False,
        "show_in_list_default": True,
        "is_unique": True,
        "storage": "db",
        "sort_order": 5,
    },
    {
        "field_key": "title",
        "label": "任务主题",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {
        "field_key": "description",
        "label": "任务描述",
        "field_type": "textarea",
        "storage": "db",
        "sort_order": 20,
    },
    {
        "field_key": "status",
        "label": "状态",
        "field_type": "select",
        "options": ["open", "in_progress", "done", "cancelled"],
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 30,
    },
    {
        "field_key": "priority",
        "label": "优先级",
        "field_type": "select",
        "options": ["low", "normal", "high"],
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 40,
    },
    {
        "field_key": "due_at",
        "label": "截止时间",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 50,
    },
    {
        "field_key": "assignee_user_id",
        "label": "执行人",
        "field_type": "user_ref",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 60,
    },
    {"field_key": "lead_id", "label": "关联线索", "field_type": "ref", "storage": "db", "sort_order": 70},
    {"field_key": "customer_id", "label": "关联客户", "field_type": "ref", "storage": "db", "sort_order": 80},
]

CAMPAIGN_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "campaign_number",
        "label": "活动编号",
        "field_type": "text",
        "is_required": False,
        "show_in_list_default": True,
        "is_unique": True,
        "storage": "db",
        "sort_order": 5,
    },
    {
        "field_key": "name",
        "label": "活动名称",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {
        "field_key": "status",
        "label": "活动状态",
        "field_type": "select",
        "options": ["draft", "active", "ended"],
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 20,
    },
    {"field_key": "start_at", "label": "开始日期", "field_type": "datetime", "storage": "db", "sort_order": 30},
    {"field_key": "end_at", "label": "结束日期", "field_type": "datetime", "storage": "db", "sort_order": 40},
    {"field_key": "channels", "label": "渠道", "field_type": "multiselect", "sort_order": 50},
    {"field_key": "goal", "label": "目标", "field_type": "textarea", "storage": "db", "sort_order": 60},
    {
        "field_key": "owner_user_id",
        "label": "负责人",
        "field_type": "user_ref",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 70,
    },
    {"field_key": "budget", "label": "预算", "field_type": "currency", "sort_order": 80},
]

# ============================================================
# v0.7 CRM-2/3：商机 / 报价 / 合同 / 订单 / 收款 / 产品
# ============================================================

DEAL_STATUS_OPTIONS = ["open", "won", "lost", "abandoned"]

DEAL_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "deal_number",
        "label": "商机编号",
        "field_type": "text",
        "is_required": False,
        "show_in_list_default": True,
        "is_unique": True,
        "storage": "db",
        "sort_order": 5,
    },
    {
        "field_key": "title",
        "label": "商机名称",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {
        "field_key": "customer_id",
        "label": "客户",
        "field_type": "ref",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 20,
    },
    {"field_key": "contact_id", "label": "主要联系人", "field_type": "ref", "storage": "db", "sort_order": 30},
    {
        "field_key": "pipeline_id",
        "label": "销售管道",
        "field_type": "ref",
        "is_required": True,
        "storage": "db",
        "sort_order": 40,
    },
    {
        "field_key": "stage_id",
        "label": "阶段",
        "field_type": "ref",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 50,
    },
    {
        "field_key": "amount",
        "label": "商机金额",
        "field_type": "currency",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 60,
    },
    {
        "field_key": "expected_close_date",
        "label": "预计成交日",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 70,
    },
    {
        "field_key": "probability",
        "label": "成交概率",
        "field_type": "number",
        "storage": "db",
        "sort_order": 80,
    },
    {
        "field_key": "status",
        "label": "商机状态",
        "field_type": "select",
        "options": DEAL_STATUS_OPTIONS,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 90,
    },
    {"field_key": "loss_reason", "label": "输单原因", "field_type": "text", "storage": "db", "sort_order": 100},
    {
        "field_key": "source",
        "label": "商机来源",
        "field_type": "select",
        "options": list(DEAL_SOURCES),
        "storage": "db",
        "sort_order": 110,
    },
    {"field_key": "campaign_id", "label": "营销活动", "field_type": "ref", "storage": "db", "sort_order": 120},
    {"field_key": "description", "label": "需求描述", "field_type": "textarea", "storage": "db", "sort_order": 125},
    {"field_key": "next_step", "label": "下一步", "field_type": "text", "storage": "db", "sort_order": 126},
    {
        "field_key": "deal_type",
        "label": "商机类型",
        "field_type": "select",
        "options": ["新业务", "续约", "升级", "交叉销售"],
        "storage": "db",
        "sort_order": 127,
    },
    {
        "field_key": "priority",
        "label": "优先级",
        "field_type": "select",
        "options": ["high", "medium", "low"],
        "storage": "db",
        "show_in_list_default": True,
        "sort_order": 128,
    },
    {"field_key": "competitor", "label": "竞争对手", "field_type": "text", "storage": "db", "sort_order": 129},
    {
        "field_key": "contact_role",
        "label": "联系人角色",
        "field_type": "select",
        "options": ["决策者", "影响者", "使用者", "评估者"],
        "storage": "db",
        "sort_order": 130,
    },
    {"field_key": "converted_from_lead_id", "label": "来源线索", "field_type": "ref", "storage": "db", "sort_order": 135},
    {"field_key": "converted_order_id", "label": "转出订单", "field_type": "ref", "storage": "db", "sort_order": 140},
    {"field_key": "closed_at", "label": "成交时间", "field_type": "datetime", "storage": "db", "sort_order": 150},
]

QUOTE_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "quote_number",
        "label": "报价单号",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {"field_key": "deal_id", "label": "关联商机", "field_type": "ref", "storage": "db", "sort_order": 20},
    {
        "field_key": "customer_id",
        "label": "客户",
        "field_type": "ref",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 30,
    },
    {"field_key": "contact_id", "label": "联系人", "field_type": "ref", "storage": "db", "sort_order": 40},
    {
        "field_key": "subject",
        "label": "报价主题",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 50,
    },
    {"field_key": "discount_rate", "label": "整单折扣%", "field_type": "number", "storage": "db", "sort_order": 60},
    {
        "field_key": "total_amount",
        "label": "报价总额",
        "field_type": "currency",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 70,
    },
    {
        "field_key": "status",
        "label": "报价状态",
        "field_type": "select",
        "options": list(QUOTE_STATUSES),
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 80,
    },
    {"field_key": "valid_until", "label": "有效期", "field_type": "datetime", "storage": "db", "sort_order": 90},
    {"field_key": "converted_order_id", "label": "转出订单", "field_type": "ref", "storage": "db", "sort_order": 100},
]

CONTRACT_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "contract_number",
        "label": "合同编号",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {"field_key": "deal_id", "label": "关联商机", "field_type": "ref", "storage": "db", "sort_order": 20},
    {
        "field_key": "customer_id",
        "label": "客户",
        "field_type": "ref",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 30,
    },
    {"field_key": "quote_id", "label": "来源报价", "field_type": "ref", "storage": "db", "sort_order": 40},
    {
        "field_key": "title",
        "label": "合同标题",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 50,
    },
    {
        "field_key": "contract_type",
        "label": "合同类型",
        "field_type": "select",
        "options": list(CONTRACT_TYPES),
        "storage": "db",
        "sort_order": 60,
    },
    {
        "field_key": "amount",
        "label": "合同金额",
        "field_type": "currency",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 70,
    },
    {"field_key": "signed_amount", "label": "签署金额", "field_type": "currency", "storage": "db", "sort_order": 80},
    {
        "field_key": "start_date",
        "label": "服务开始",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 90,
    },
    {
        "field_key": "end_date",
        "label": "服务结束",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 100,
    },
    {
        "field_key": "status",
        "label": "合同状态",
        "field_type": "select",
        "options": list(CONTRACT_STATUSES),
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 110,
    },
    {"field_key": "signed_at", "label": "签署时间", "field_type": "datetime", "storage": "db", "sort_order": 120},
    {"field_key": "file_url", "label": "合同附件", "field_type": "text", "storage": "db", "sort_order": 130},
]

ORDER_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "order_number",
        "label": "订单号",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {
        "field_key": "title",
        "label": "订单主题",
        "field_type": "text",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 20,
    },
    {
        "field_key": "customer_id",
        "label": "客户",
        "field_type": "ref",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 30,
    },
    {"field_key": "contact_id", "label": "联系人", "field_type": "ref", "storage": "db", "sort_order": 40},
    {"field_key": "deal_id", "label": "关联商机", "field_type": "ref", "storage": "db", "sort_order": 50},
    {"field_key": "quote_id", "label": "来源报价", "field_type": "ref", "storage": "db", "sort_order": 60},
    {"field_key": "contract_id", "label": "来源合同", "field_type": "ref", "storage": "db", "sort_order": 70},
    {
        "field_key": "source",
        "label": "订单来源",
        "field_type": "select",
        "options": list(ORDER_SOURCES),
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 80,
    },
    {
        "field_key": "order_date",
        "label": "下单日期",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 90,
    },
    {
        "field_key": "amount",
        "label": "订单金额",
        "field_type": "currency",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 100,
    },
    {
        "field_key": "status",
        "label": "订单状态",
        "field_type": "select",
        "options": list(ORDER_STATUSES),
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 110,
    },
]

PAYMENT_METHOD_OPTIONS = list(PAYMENT_METHODS)
PAYMENT_STATUS_OPTIONS = list(PAYMENT_STATUSES)

PAYMENT_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "payment_number",
        "label": "回款单号",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {
        "field_key": "order_id",
        "label": "关联订单",
        "field_type": "ref",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 20,
    },
    {"field_key": "plan_id", "label": "关联回款计划", "field_type": "ref", "storage": "db", "sort_order": 30},
    {
        "field_key": "amount",
        "label": "回款金额",
        "field_type": "currency",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 40,
    },
    {
        "field_key": "paid_at",
        "label": "到账日期",
        "field_type": "datetime",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 50,
    },
    {
        "field_key": "method",
        "label": "回款方式",
        "field_type": "select",
        "options": PAYMENT_METHOD_OPTIONS,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 60,
    },
    {
        "field_key": "status",
        "label": "回款状态",
        "field_type": "select",
        "options": PAYMENT_STATUS_OPTIONS,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 70,
    },
    {"field_key": "remark", "label": "备注", "field_type": "textarea", "storage": "db", "sort_order": 80},
]

PRODUCT_FIELDS: list[dict[str, Any]] = [
    {
        "field_key": "code",
        "label": "产品编码",
        "field_type": "text",
        "is_required": True,
        "is_unique": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 10,
    },
    {
        "field_key": "name",
        "label": "产品名称",
        "field_type": "text",
        "is_required": True,
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 20,
    },
    {"field_key": "unit", "label": "单位", "field_type": "text", "storage": "db", "sort_order": 30},
    {
        "field_key": "list_price",
        "label": "标价",
        "field_type": "currency",
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 40,
    },
    {"field_key": "cost_price", "label": "成本价", "field_type": "currency", "storage": "db", "sort_order": 50},
    {
        "field_key": "is_active",
        "label": "启用",
        "field_type": "select",
        "options": ["是", "否"],
        "show_in_list_default": True,
        "storage": "db",
        "sort_order": 60,
    },
    {"field_key": "description", "label": "描述", "field_type": "textarea", "storage": "db", "sort_order": 70},
]

ENTITY_SEED_MAP: dict[str, list[dict[str, Any]]] = {
    "lead": COMMON_FIELDS + LEAD_FIELDS,
    "customer": COMMON_FIELDS + CUSTOMER_FIELDS,
    "contact": CONTACT_FIELDS,
    "task": COMMON_FIELDS + TASK_FIELDS,
    "campaign": COMMON_FIELDS + CAMPAIGN_FIELDS,
    # v0.7 CRM-2/3
    "deal": COMMON_FIELDS + DEAL_FIELDS,
    "quote": COMMON_FIELDS + QUOTE_FIELDS,
    "contract": COMMON_FIELDS + CONTRACT_FIELDS,
    "order": COMMON_FIELDS + ORDER_FIELDS,
    "payment": COMMON_FIELDS + PAYMENT_FIELDS,
    "product": PRODUCT_FIELDS,
}

LEAD_LABEL_EXPECTATIONS: dict[str, str] = {
    "company_name": "公司名称",
    "contact_name": "联系人姓名",
    "mobile": "手机",
    "source": "线索来源",
    "status": "线索状态",
    "owner_user_id": "负责人",
    "territory_id": "归属地区",
    "industry": "行业",
    "intention_level": "意向等级",
}
